In [ ]:
#---------With hstack we can appened data horizontally

In [9]:
import numpy as np

arr = np.array([[10, 20, 30, 45, 34], [12, 34, 54, 65, 75]])
arr1 = np.array([[33, 43, 56, 98, 99], [123, 45, 65, 76, 90]])
arr2 = np.array([[38, 43, 96, 8, 9], [12, 4, 6, 76, 9]])
np.hstack([arr])

array([[10, 20, 30, 45, 34],
       [12, 34, 54, 65, 75]])

In [10]:
np.hstack([arr,arr1])

array([[ 10,  20,  30,  45,  34,  33,  43,  56,  98,  99],
       [ 12,  34,  54,  65,  75, 123,  45,  65,  76,  90]])

In [11]:
np.hstack([arr,arr1,arr2])

array([[ 10,  20,  30,  45,  34,  33,  43,  56,  98,  99,  38,  43,  96,
          8,   9],
       [ 12,  34,  54,  65,  75, 123,  45,  65,  76,  90,  12,   4,   6,
         76,   9]])

In [ ]:
#--------With vstack we can appened data vertically

In [6]:
np.vstack([arr])

array([[10, 20, 30, 45, 34],
       [12, 34, 54, 65, 75]])

In [7]:
np.vstack([arr,arr1])

array([[ 10,  20,  30,  45,  34],
       [ 12,  34,  54,  65,  75],
       [ 33,  43,  56,  98,  99],
       [123,  45,  65,  76,  90]])

In [8]:
np.vstack([arr,arr1,arr2])

array([[ 10,  20,  30,  45,  34],
       [ 12,  34,  54,  65,  75],
       [ 33,  43,  56,  98,  99],
       [123,  45,  65,  76,  90],
       [ 33,  43,  56,  98,  99],
       [123,  45,  65,  76,  90]])